### ISSUE TITLE
Actividad 2- Practica de interfaz

### ISSUE THREAD

**Issue by Blanca-estela-valerio-rivero** [SistemasTecTlaxiaco/actividad-2de-practica-interfaz-grafica-con-c-confident-students#1]
[PRACTICA 2_ Interfaz Grafica .pdf](https://github.com/SistemasTecTlaxiaco/actividad-2de-practica-interfaz-grafica-con-c-confident-students/files/14317053/PRACTICA.2_.Interfaz.Grafica.pdf)
 
Integrantes del equipo:
García Santiago Sandy Marissa
 Sarmiento Ruiz Edgar Mauricio
 Valerio Rivero Blanca Estela

**Comment by IrvinSanchez-dev** [comment]
Dado a la rubrica de evaluación, obtuvieron 20% de 20%

**Se encontraron algunas faltas de puntuación y de ortografia, pero en general todo está bien.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
